<script src="<?= base_url() ?>/assets/js/bootstrap.bundle.min.js"></script>
<script src="<?= base_url() ?>/assets/js/slideToggle.min.js"></script>
<script src="<?= base_url() ?>/assets/js/internet-status.js"></script>
<script src="<?= base_url() ?>/assets/js/tiny-slider.js"></script>
<script src="<?= base_url() ?>/assets/js/venobox.min.js"></script>
<script src="<?= base_url() ?>/assets/js/countdown.js"></script>
<script src="<?= base_url() ?>/assets/js/rangeslider.min.js"></script>
<script src="<?= base_url() ?>/assets/js/vanilla-dataTables.min.js"></script>
<script src="<?= base_url() ?>/assets/js/index.js"></script>
<script src="<?= base_url() ?>/assets/js/imagesloaded.pkgd.min.js"></script>
<script src="<?= base_url() ?>/assets/js/isotope.pkgd.min.js"></script>
<script src="<?= base_url() ?>/assets/js/dark-rtl.js"></script>
<script src="<?= base_url() ?>/assets/js/active.js"></script>
<script src="<?= base_url() ?>/assets/js/pwa.js"></script>
<script src="<?= base_url() ?>/assets/js/pswmeter.js"></script>
<script src="<?= base_url() ?>/assets/js/index.js"></script>